### ISSUE TITLE
Remove details prop or restrict it

### ISSUE THREAD

**Issue by aaronshaf** [RangerMauve/dat-pub#4]
It seems like the `details` prop in the POST body could be a recipe for trouble. Someone could flood the archive with very large payloads. Can I remove this for now until it is well-defined with some restrictions?

**Comment by RangerMauve** [comment]
I'm all for it! I wasn't totally sure what to put in there anyways. :D

**Comment by RangerMauve** [comment]
What do you think about replacing it with a `Date.now()` timestamp?

**Comment by aaronshaf** [comment]
Replacing the `{}`? Can you be more specific? Perhaps:

```
{
  "lastUpdated": Date.now
}
```

?

**Comment by RangerMauve** [comment]
I was originally thinking just the timestamp, but having `lastUpdated` in an object would be better in case there's more useful information that could be put there in the future.
